export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const MODULE_ROUTES = {
  dashboard: ['/dashboard'],
  leaderboards: ['/dashboard/leaderboards'],
  employee_data: ['/dashboard/employee-data'],
  department_management: ['/dashboard/departments', '/dashboard/positions'],
  attendance_management: ['/dashboard/attendance-management'],
  schedules: ['/dashboard/schedule-management', '/dashboard/schedule-management/create'],
  leave_management: ['/dashboard/leave-management'],
  payroll_management: ['/dashboard/payroll', '/dashboard/payroll/history', '/dashboard/payroll/generate', '/dashboard/payroll/13th-month'],
  holidays: ['/dashboard/holiday-management'],
  contributions: ['/dashboard/contributions-management'],
  performance_management: ['/dashboard/performance'],
  training_and_development: ['/dashboard/training'],
  predictive_analytics: ['/dashboard/predictive-analytics'],
  case_management: ['/dashboard/case-management'],
  resignation_management: ['/dashboard/resignation-management'],
  recruitment: ['/dashboard/recruitment'],
  accounts_management: ['/dashboard/accounts'],
  reports: ['/dashboard/reports'],
  my_team: ['/dashboard/team-employees'],
  submit_evaluation: ['/dashboard/evaluate-team', '/dashboard/evaluate-leader', '/dashboard/performance/evaluate'],
  my_leave: ['/dashboard/my-leave'],
  my_cases: ['/dashboard/my-cases'],
  submit_incident_report: ['/dashboard/submit-report'],
  my_attendance: ['/dashboard/my-attendance'],
  my_resignation: ['/dashboard/my-resignation'],
  my_payroll: ['/dashboard/my-payroll', '/dashboard/my-payroll/projection'],
  my_profile: ['/dashboard/my-profile'],
  account_settings: ['/dashboard/account-settings'],
};

export const ROLE_ALLOWED_ROUTES = {
  [USER_ROLES.SUPER_ADMIN]: [
    '/dashboard',
    '/dashboard/employee-data',
    '/dashboard/leaderboards',
    '/dashboard/positions',
    '/dashboard/departments',
    '/dashboard/attendance-management',
    '/dashboard/schedule-management',
    '/dashboard/schedule-management/create',
    '/dashboard/leave-management',
    '/dashboard/payroll',
    '/dashboard/payroll/history',
    '/dashboard/payroll/generate',
    '/dashboard/payroll/13th-month',
    '/dashboard/holiday-management',
    '/dashboard/contributions-management',
    '/dashboard/performance',
    '/dashboard/training',
    '/dashboard/predictive-analytics',
    '/dashboard/case-management',
    '/dashboard/resignation-management',
    '/dashboard/recruitment',
    '/dashboard/reports',
    '/dashboard/my-profile',
    '/dashboard/account-settings',
    '/dashboard/accounts',
  ],
};