export const USER_ROLES = {
  HR_PERSONNEL: 'HR_PERSONNEL',
  TEAM_LEADER: 'TEAM_LEADER',
  REGULAR_EMPLOYEE: 'REGULAR_EMPLOYEE',
};

export const ROLE_ALLOWED_ROUTES = {
  [USER_ROLES.HR_PERSONNEL]: [
    '/dashboard',
    '/dashboard/employee-data',
    '/dashboard/leaderboards',
    '/dashboard/positions',
    '/dashboard/attendance-management',
    '/dashboard/schedule-management',
    '/dashboard/schedule-management/create',
    '/dashboard/leave-management',
    '/dashboard/payroll',
    '/dashboard/payroll/history',
    '/dashboard/payroll/generate',
    '/dashboard/payroll/13th-month',
    '/dashboard/holiday-management',
    '/dashboard/contributions-management',
    '/dashboard/performance',
    '/dashboard/training',
    '/dashboard/predictive-analytics',
    '/dashboard/case-management',
    '/dashboard/resignation-management',
    '/dashboard/recruitment',
    '/dashboard/reports',
    '/dashboard/my-profile',
    '/dashboard/account-settings',
    '/dashboard/accounts',
  ],
  [USER_ROLES.TEAM_LEADER]: [
    '/dashboard',
    '/dashboard/team-employees',
    '/dashboard/evaluate-team',
    '/dashboard/evaluate-leader',
    '/dashboard/performance/evaluate',
    '/dashboard/my-leave',
    '/dashboard/my-attendance',
    '/dashboard/my-cases',
    '/dashboard/submit-report',
    '/dashboard/my-payroll',
    '/dashboard/my-resignation',
    '/dashboard/my-profile',
    '/dashboard/account-settings',
  ],
  [USER_ROLES.REGULAR_EMPLOYEE]: [
    '/dashboard',
    '/dashboard/team-employees',
    '/dashboard/evaluate-leader',
    '/dashboard/performance/evaluate',
    '/dashboard/my-leave',
    '/dashboard/my-attendance',
    '/dashboard/my-cases',
    '/dashboard/submit-report',
    '/dashboard/my-payroll',
    '/dashboard/my-resignation',
    '/dashboard/my-profile',
    '/dashboard/account-settings',
  ],
};